import { HandleError } from "@/utils";

export async function GET(req: Request) {
  try {
  } catch (err) {
    return HandleError(err);
  }
}
